# Orig file: build/target/etc/pulse/daemon.conf

daemonize = yes
disallow-exit = yes
exit-idle-time = -1
use-pid-file = yes
enable-shm = no

resample-method = speex-fixed-1
default-sample-rate = 48000
alternate-sample-rate = 48000
